;;;; package.lisp

(defpackage #:matrix
  (:use #:cl)
  (:export #:matrix
           #:matrix-rows
           #:matrix-cols
           #:matrix-type
           #:matrix-data
           #:matrix-p
           #:mref
           #:m+
           #:madd
           #:m-
           #:msub
           #:m*
           #:mmul
           #:diag
           #:diagf
           #:diagp
           #:diagonalf
           #:diagonal-matrix
           #:diagonal-matrix-p
           #:eye
           #:eyep
           #:identity-matrix
           #:identity-matrix-p
           #:copy-matrix
           #:mexpt
           #:trans
           #:mapeach
           #:row-echelon
           #:row-canonical
           #:col-canonical
           #:canonical
           #:rank
           #:row-rank
           #:col-rank
           #:inv
           #:det
           #:inversion
           #:submatrix
           #:minor
           #:cofactor
           #:signed-minor
           #:adj
           #:tr
           #:dot
           #:dot-*
           #:msum
           #:norm
           #:euclidean-distance
           #:permutation
           #:gen-seq-vec
           #:matrix-row-multiplyf
           #:matrix-row-addf
           #:matrix-row-switchf
           #:matrix-col-multiplyf
           #:matrix-col-addf
           #:matrix-col-switchf
           #:rearrangef
           #:matrix-dimentions
           #:with-i-j
           #:i
           #:j
           #:with-matrix
           #:rows
           #:cols
           #:type
           #:data
           #:*default-type*))
